version: '3.8'

services:
  manager:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - app-net

  worker:
    image: alpine:latest
    command: ["sleep", "3600"]
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
